//FLAGS Encoded on 1 bytes
export enum Flags {
  OPEN_DOC = "OPEN_DOC",
  WRITE_DOC = "WRITE_DOC",
  CURSOR_DOC = "CURSOR_DOC",
  REMOVE_DOC = "REMOVE_DOC",
  TAG_ADD_DOC = "TAG_ADD_DOC",
  TAG_REMOVE_DOC = "TAG_REMOVE_DOC",

  CREATE_TAG = "CREATE_TAG",
  REMOVE_TAG = "REMOVE_TAG",
  UPDATE_TAG = "UPDATE_TAG",

  OPEN_PROJECT = "OPEN_PROJECT",
  CLOSE_PROJECT = "CLOSE_PROJECT",

  MOVE_FILE = "MOVE_FILE",
  RENAME_FILE = "RENAME_FILE",
  COPY_FILE = "COPY_FILE",
  GET_FILE = "GET_FILE"
}